### ISSUE TITLE
import F5 OVA into AWS Failed with message - StatusMessage": "ClientError: Unsupported: Incomplete root disk: Missing kernel configuration file"

### ISSUE THREAD

**Issue by meluuans** [rjocoleman/oracle-linux-ami-builder#3]
Greetings,

I am trying to import BIGIP OVA into aws but it fails during the import. I tried both using RedHat and aws linux with no luck.  
Also, the format changes during the import to EC2 as shown below. Is that expected? 

Appreciate the support.
-meluuans

****import script -**** 
aws ec2 import-image --description "vf5 VM" --disk-containers "file://containers.json/"

[
  {
    "Description": "My Server OVA",
    "Format": "ova",
    "Url": "s3://f5-images/BIGIP-16.1.3.3-0.0.3.ALL-vmware.ova"
  }
]

===================================================
**Task check -** 

"Description": "vf5 VM",
    "ImportTaskId": "import-ami-xyxxxxxyx",
    "Progress": "1",
    "SnapshotDetails": [
        {
            "Description": "My Server OVA",
            "DiskImageSize": 0.0,
            "Format": "OVA",
            "Url": "s3://f5-images/BIGIP-16.1.3.3-0.0.3.ALL-vmware.ova",
            "UserBucket": {
                "S3Bucket": "f5-images",
                "S3Key": "BIGIP-16.1.3.3-0.0.3.ALL-vmware.ova"
            }
        }
    ],
    "Status": "active",
    "StatusMessage": "pending"

=========
"ImportImageTasks": [
        {
            "Description": "vf5 VM",
            "ImportTaskId": "import-ami-xyxxxxxyx",
            "SnapshotDetails": [
                {
                    "DeviceName": "/dev/sde",
                    "DiskImageSize": 2515319808.0,
                    "Format": "VMDK",                                                          **<------------------Format changed to VMDK**
                    "Status": "completed",
                    "Url": "s3://f5-images/BIGIP-16.1.3.3-0.0.3.ALL-vmware.ova",
                    "UserBucket": {
                        "S3Bucket": "f5-images",
                        "S3Key": "BIGIP-16.1.3.3-0.0.3.ALL-vmware.ova"
                    }
                }
            ],
            "Status": "deleted",
            "StatusMessage": "ClientError: Unsupported: Incomplete root disk: Missing kernel configuration file",
            "Tags": []
        }
    ]
}

**Comment by meluuans** [comment]
fyi, this is my first time posting. Apology if I missed any important data :)

**Comment by rjocoleman** [comment]
Sorry, I haven't used this in around 7 years and don't remeber any of the details nor use any of the technology at present - I'm going to archive the repo as I can't support it
